// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeO0tHhp0D4fced96fcA76L1IQIdfyH8A',
    appId: '1:211839556822:web:f898db408b3533c4a2fd77',
    messagingSenderId: '211839556822',
    projectId: 'vibe-note',
    authDomain: 'vibe-note.firebaseapp.com',
    storageBucket: 'vibe-note.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0kJjxlvkmCmEaSz-A2KavGQbwGBsqeGw',
    appId: '1:211839556822:android:6fc3f607499d90b2a2fd77',
    messagingSenderId: '211839556822',
    projectId: 'vibe-note',
    storageBucket: 'vibe-note.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRE52zc5Ad5vskT5QC27j0PSVmji3Tp8',
    appId: '1:211839556822:ios:6afab23e757e650fa2fd77',
    messagingSenderId: '211839556822',
    projectId: 'vibe-note',
    storageBucket: 'vibe-note.firebasestorage.app',
    iosBundleId: 'com.example.vibeNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzRE52zc5Ad5vskT5QC27j0PSVmji3Tp8',
    appId: '1:211839556822:ios:6afab23e757e650fa2fd77',
    messagingSenderId: '211839556822',
    projectId: 'vibe-note',
    storageBucket: 'vibe-note.firebasestorage.app',
    iosBundleId: 'com.example.vibeNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeO0tHhp0D4fced96fcA76L1IQIdfyH8A',
    appId: '1:211839556822:web:6e3cca82d194349da2fd77',
    messagingSenderId: '211839556822',
    projectId: 'vibe-note',
    authDomain: 'vibe-note.firebaseapp.com',
    storageBucket: 'vibe-note.firebasestorage.app',
  );
}
